### ISSUE TITLE
No reader function for tag clj-time/date-time.

### ISSUE THREAD

**Issue by mauricioszabo** [ryrobes/rvbbit#4] opened 2024-09-03 15:23 UTC
Hi, first of all, thanks for this project!

So, I tried to drag a PostgreSQL table into the canvas, but all I get is a empty black window. At the devtools console I get the error `No reader function for tag clj-time/date-time.`

Please let me know if I can help with more info :+1:

**Comment by ryrobes** [comment] 2024-09-04 00:46
Heya, thanks for the heads up and giving it a try. 

I kind of expected this (JDBC loves to sneak java objects into resultsets), but couldn't reproduce. What data types was your table using? I just tried and wasn't able to get the blank card and error. Using postgres.

```
CREATE TABLE datetime_test (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    event_date DATE,
    event_time TIME,
    event_timestamp TIMESTAMP,
    event_timestamptz TIMESTAMPTZ
);

INSERT INTO datetime_test (name, event_date, event_time, event_timestamp, event_timestamptz)
VALUES
    ('Event 1', '2023-05-15', '14:30:00', '2023-05-15 14:30:00', '2023-05-15 14:30:00+00'),
    ('Event 2', '2023-06-20', '09:15:00', '2023-06-20 09:15:00', '2023-06-20 09:15:00+00'),
    ('Event 3', '2023-07-04', '18:45:00', '2023-07-04 18:45:00', '2023-07-04 18:45:00+00'),
    ('Event 4', '2023-08-10', '11:00:00', '2023-08-10 11:00:00', '2023-08-10 11:00:00+00'),
    ('Event 5', CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
```

And then just some drag and drops in Rabbit.. seemed to work? 

![image](https://github.com/user-attachments/assets/5c255634-4643-4f7f-a06f-3de710f05743)

Again, I might just look for Java Inst times and convert them anyways, since the UI will def not support that - but I'd love to confirm. Let me know if I missed something, test-wise!

**Comment by Guliy** [comment] 2024-09-04 17:14
I have a similar issue, but with the ::jsonb data type. If I remove the fields with unknown data types, the data starts to display correctly.

![Screenshot 2024-09-04 at 20 05 09](https://github.com/user-attachments/assets/ec254617-c223-49c2-a83c-e104ae1de4b7)

![Screenshot 2024-09-04 at 20 14 20](https://github.com/user-attachments/assets/6de28d58-4faa-459c-aa53-f52208435a27)

**Comment by ryrobes** [comment] 2024-09-06 03:09
Cool thanks, very helpful. What I'm going to do it make sure that rowset sent to the client is stringified if it's an object (since at the moment its not useful from the grid UI - _although there could def be some cool "map interactions" with json/jsonb/etc as legit EDN w UI around it in the future_) - BUT, I'll make sure that if a REPL client tries to access query data (via :data/query-name) that the original data is preserved, so objects can be used natively if sent back from JDBC that way. 

Will be in the next release this weekend most likely.

**Comment by Guliy** [comment] 2024-09-06 06:58
As a workaround, now I just make a view and use it, turning the data I need from json into columns. But, of course, this does not solve the problem in the general case.

Anyway, thank you for your fantastic work. I'm thrilled!

**Closed** 2024-09-16 00:43 UTC
